#!/bin/bash
# Step 1: Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
# Step 2: Restart terminal
# Step 3: Install Node.js
nvm install 20.16
# Step 4: Install Sass
npm install sass@3.7.4
